huh:
  encore:
    entries:
      - { name: contao-menu-bundle, requiresCss: true, file: "vendor/heimrichhannot/contao-menu-bundle/src/Resources/assets/js/contao-menu-bundle.js"}
    legacy:
      js:
        - contao-menu-bundle
      css:
        - contao-menu-bundle